[package]
name = "zyberlink_aptos"
version = "0.1.0"
edition = "2024.beta"

[addresses]
zyberlink = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "main" }

[dev-dependencies]
