//! E2E test for ZK attestation flow with all circuit types
//!
//! Tests that the AttestationService can:
//! 1. Load verification keys for all 8 circuit types
//! 2. Verify proofs generated by the circuits
//! 3. Generate attestation witnesses

use std::path::PathBuf;

mod common;

/// Get the verification keys directory
fn get_vk_directory() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("verification_keys")
}

/// Get the test proofs directory
fn get_test_proofs_directory() -> PathBuf {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".to_string());
    PathBuf::from(manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("circuits")
        .join("test-proofs")
        .join("outputs")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_vk_directory_exists() {
        let vk_dir = get_vk_directory();
        assert!(vk_dir.exists(), "VK directory should exist: {:?}", vk_dir);
    }

    #[test]
    fn test_all_vkeys_exist() {
        let vk_dir = get_vk_directory();
        let expected_circuits = [10, 20, 21, 30, 31, 32, 40, 41];

        for circuit_id in expected_circuits {
            let vk_path = vk_dir.join(format!("circuit_{}_vkey.json", circuit_id));
            assert!(
                vk_path.exists(),
                "VKey for circuit {} should exist: {:?}",
                circuit_id,
                vk_path
            );
        }
    }

    #[test]
    fn test_all_proofs_exist() {
        let proofs_dir = get_test_proofs_directory();
        let expected_circuits = [10, 20, 21, 30, 31, 32, 40, 41];

        for circuit_id in expected_circuits {
            let proof_path = proofs_dir.join(format!("circuit_{}_proof.json", circuit_id));
            let public_path = proofs_dir.join(format!("circuit_{}_public.json", circuit_id));

            assert!(
                proof_path.exists(),
                "Proof for circuit {} should exist: {:?}",
                circuit_id,
                proof_path
            );
            assert!(
                public_path.exists(),
                "Public inputs for circuit {} should exist: {:?}",
                circuit_id,
                public_path
            );
        }
    }

    #[test]
    fn test_vkey_json_valid() {
        let vk_dir = get_vk_directory();
        let expected_circuits = [10, 20, 21, 30, 31, 32, 40, 41];

        for circuit_id in expected_circuits {
            let vk_path = vk_dir.join(format!("circuit_{}_vkey.json", circuit_id));
            let vk_content = std::fs::read_to_string(&vk_path)
                .expect(&format!("Failed to read VKey for circuit {}", circuit_id));

            let vk: serde_json::Value = serde_json::from_str(&vk_content)
                .expect(&format!("Failed to parse VKey JSON for circuit {}", circuit_id));

            // Check required fields
            assert!(vk.get("protocol").is_some(), "VKey {} missing protocol", circuit_id);
            assert!(vk.get("curve").is_some(), "VKey {} missing curve", circuit_id);
            assert!(vk.get("nPublic").is_some(), "VKey {} missing nPublic", circuit_id);
            assert!(vk.get("vk_alpha_1").is_some(), "VKey {} missing vk_alpha_1", circuit_id);
            assert!(vk.get("vk_beta_2").is_some(), "VKey {} missing vk_beta_2", circuit_id);
            assert!(vk.get("vk_gamma_2").is_some(), "VKey {} missing vk_gamma_2", circuit_id);
            assert!(vk.get("vk_delta_2").is_some(), "VKey {} missing vk_delta_2", circuit_id);
            assert!(vk.get("IC").is_some(), "VKey {} missing IC", circuit_id);

            // Verify protocol and curve
            assert_eq!(
                vk["protocol"].as_str().unwrap(),
                "groth16",
                "VKey {} should have groth16 protocol",
                circuit_id
            );
            assert_eq!(
                vk["curve"].as_str().unwrap(),
                "bn128",
                "VKey {} should have bn128 curve",
                circuit_id
            );
        }
    }

    #[test]
    fn test_proof_json_valid() {
        let proofs_dir = get_test_proofs_directory();
        let expected_circuits = [10, 20, 21, 30, 31, 32, 40, 41];

        for circuit_id in expected_circuits {
            let proof_path = proofs_dir.join(format!("circuit_{}_proof.json", circuit_id));
            let proof_content = std::fs::read_to_string(&proof_path)
                .expect(&format!("Failed to read proof for circuit {}", circuit_id));

            let proof: serde_json::Value = serde_json::from_str(&proof_content)
                .expect(&format!("Failed to parse proof JSON for circuit {}", circuit_id));

            // Check required fields
            assert!(proof.get("pi_a").is_some(), "Proof {} missing pi_a", circuit_id);
            assert!(proof.get("pi_b").is_some(), "Proof {} missing pi_b", circuit_id);
            assert!(proof.get("pi_c").is_some(), "Proof {} missing pi_c", circuit_id);
            assert!(proof.get("protocol").is_some(), "Proof {} missing protocol", circuit_id);
            assert!(proof.get("curve").is_some(), "Proof {} missing curve", circuit_id);

            // Verify protocol and curve
            assert_eq!(
                proof["protocol"].as_str().unwrap(),
                "groth16",
                "Proof {} should have groth16 protocol",
                circuit_id
            );
            assert_eq!(
                proof["curve"].as_str().unwrap(),
                "bn128",
                "Proof {} should have bn128 curve",
                circuit_id
            );
        }
    }

    /// Test public inputs count matches VKey nPublic
    #[test]
    fn test_public_inputs_count_matches() {
        let vk_dir = get_vk_directory();
        let proofs_dir = get_test_proofs_directory();
        let expected_circuits = [10, 20, 21, 30, 31, 32, 40, 41];

        for circuit_id in expected_circuits {
            // Read VKey
            let vk_path = vk_dir.join(format!("circuit_{}_vkey.json", circuit_id));
            let vk_content = std::fs::read_to_string(&vk_path).unwrap();
            let vk: serde_json::Value = serde_json::from_str(&vk_content).unwrap();
            let n_public = vk["nPublic"].as_u64().unwrap() as usize;

            // Read public inputs
            let public_path = proofs_dir.join(format!("circuit_{}_public.json", circuit_id));
            let public_content = std::fs::read_to_string(&public_path).unwrap();
            let public_inputs: Vec<String> = serde_json::from_str(&public_content).unwrap();

            assert_eq!(
                public_inputs.len(),
                n_public,
                "Circuit {} public inputs count ({}) should match nPublic ({})",
                circuit_id,
                public_inputs.len(),
                n_public
            );
        }
    }
}
