
[sncast.devnet]
account = "devnet-deployer"
accounts-file = "/root/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://devnet:5050"

[sncast.prover2]
account = "prover2"
accounts-file = "/root/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://devnet:5050"
