[package]
name = "fhe-generator-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Client SDK for interacting with ZyberLink FHE Generator program"

[dependencies]
solana-program.workspace = true
solana-sdk.workspace = true
borsh.workspace = true
fhe-generator = { path = "../../fhe-generator", features = ["no-entrypoint"] }
bedrock-sdk = { path = "../bedrock-sdk" }
