[package]
name = "cypherlink"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "cypherlink"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program.workspace = true
borsh.workspace = true
thiserror.workspace = true

# Shared types
cypherlink-types = { path = "../../shared/types" }

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
