[package]
name = "cypherlink"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "cypherlink"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program.workspace = true
borsh.workspace = true
thiserror.workspace = true
spl-token.workspace = true
spl-associated-token-account.workspace = true
# TODO: Re-enable light-sdk when integrating zkCompression
# light-sdk.workspace = true

# Shared types
cypherlink-types.workspace = true

[dev-dependencies]
solana-program-test.workspace = true
solana-sdk.workspace = true
tokio.workspace = true
