[package]
name = "cypherlink-prover"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "cypherlink-prover"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
clap = { version = "4.4", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"

solana-sdk.workspace = true
solana-client.workspace = true

cypherlink-sdk = { path = "../sdk" }
cypherlink-types = { path = "../shared/types" }
