[package]
name = "bedrock-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Client SDK for interacting with ZyberLink Bedrock program"

[dependencies]
solana-program.workspace = true
solana-sdk.workspace = true
borsh.workspace = true
bedrock = { path = "../../bedrock", features = ["no-entrypoint"] }
